wellness/routes/about.py
from flask import render_template,Blueprint

about_page = Blueprint('about',__name__,template_folder='templates')
@about_page.route('/about',methods=['GET','POST'])

def default_about_page():
    kwargs = {
        'title': 'About',
        'jumbotron': {
            "header": "mHealth & Human",
            "bg_image": "static/images/1182_650_gallery.jpeg",
            "text": ""
        },
        'aboutPageContents': [{
            'Title': "Responsibility when providing health related content online",
            "Text": " "

        },
            {
            "Title": "Aware: technology is only small part in health care system, human play much larger role in health care procedure",
            "Text": " "

        },
            {
            "Title": "Be patient, it takes time!",
            "Text": ""

        }
        ]
    }
    return render_template('about.html', **kwargs)    

wellness/routes/activity.py
from flask import render_template,Blueprint,url_for

activity_page = Blueprint('activity',__name__,template_folder='templates')
@activity_page.route('/activity',methods=['GET','POST'])

def default_activity_page():
    kwargs = {
        'title': 'Activity',
        'jumbotron': {
            "header": "Act NOW",
            "bg_image": "static/images/1182_650_gallery.jpeg",
            "text": ""
        },
        'activityPageContents': [{
            'Title': "Physical Activities",
            "Activities": [
                {"Activities":"Go for a walk outside for 30-45 mins per day or 150 mins of moderate workout per week "},
                {"Sleep":"7-8 hours of sleep a night"},
                {"Nutrition":"1/2 Fresh fruits and veges,1/4 carb,1/4 Protain"},
                {"Breathe":"Deep breathe for 5 mins"},
                {"Standup":"Stand up once an hour for five minutes"},
                ]
        },
            {
            "Title": "Emotional Activities",
            "Activities": [
                {"Hobbies":"Find a hobby that you are passionate about. Go to therapy chat if needed."},
                {"Feelings/Emotions":"Reflect every day,use a journal to record feelings and thoughts "},
                {"Slef - Care":"Take some time to yourself regualarly; Meditation to remain calm and centered;Joined support groups if needed"},
                {"Stress":"Practice deep breathing or other relaxation; Practive finding positives in something that you feel is negative."},
                ]

        },
            {
            "Title": "Social Activities",
            "Activities": [
                {"Community":"Join groups of your interests; Find support groups if necessary"},
                {"New People":"Get out and meet people with your same interests. If you like art, try a gallery;Open to meeting people from diverse backgrounds; Find a place to volunteer"},
                {"Social Time":"Spend quality time regualary with family and friends; Make time to go to places where you can meet new people or visiting a new location; Keep track of when you need to catch up with someone.Organize a calendar of events that would be good ways to connect or reconnect, to friends, like a public concert or a class reunion"},
                ]

        },
            {
            "Title": "Intellectual Activities",
            "Activities": [
                {"Personal Interests":"Reading,music,games, teach a class,try creative arts"},
                {"Education":"Thinkabout continuing education, learn a new language "},
                {"Brain exercise":"Play brain games, mind teasers or fun memory-enhancing games, read up on current affairs locally, nationally, and internationally"},
                {"Conversation":"Take part in discussions, intellectual conversations, debates, or other ways of gaining an enhanced understanding of issues"},
                ]

        },
            {
            "Title": "Environmental Activities",
             "Activities": [
                {"Safe and calm living space":""},
                {"Green life":"Recycle and compost "},
                {"Gardening & Plant":""},
                ]

        }
        ,
            {
            "Title": "Financial Activities",
             "Activities": [
                {"Work":""},
                {"Checking/Savings Accounts":"Have a weekly or monthly budget so you can plan for expenses such as rent and groceries and have a little left over to enjoy "},
                {"Budgeting":""},
                {"Retirement/Other Accounts":"Open a savings account"},
                ]

        },
            {
            "Title": "Spiritual Activities",
             "Activities": [
                {"Meditation":"Meditation or build awareness through journaling"},
                {"Beliefs":"Share beliefs, values and principles with others, as appropriate, as a means of deepening relationships and expanding your world view"},
                {"Involvement":"Find a group that deepens your spirtual practice and helps you connect with others who share your beliefs"},
                {"Time":"Take some time everyday to meditate or reflect on your spiritually; "},
                ]

        },
            {
            "Title": "Occupational Activities",
             "Activities": [
                {"Work Relationships":""},
                {"Balance":" Schedule time for leisure or volunteer work in the community"},
                {"Accomplishment":"In a career that gives you a sense of accomplishment and pride"},
                ]

        }
        ]
    }
    return render_template('activity.html', **kwargs)    

wellness/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash
#from wellness.extensions import db
#from wellness.models import User

auth = Blueprint('auth', __name__)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form['name']
        unhashed_password = request.form['password']

        #user = User(
        #    name=name, 
        #    unhashed_password=unhashed_password,
        #    admin=False,  
        #    expert=False
        #)

        #db.session.add(user)
        #db.session.commit()

        return redirect(url_for('auth.login'))

    kwargs = {
        'title': 'Register',
        'jumbotron': {
            "header": "Sign up for an account!",
            "text": "Act now for your wellness. "
        },
        'registerPageContents': [{
            'Title': "Register"
        },

        ]
    }
    return render_template('register.html', **kwargs)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        name = request.form['name']
        password = request.form['password']

        # user = User.query.filter_by(name=name).first()

        error_message = ''

        # if not user or not check_password_hash(user.password, password):
        #     error_message = 'Could not login. Please check and try again.'

        # if not error_message:
        #     login_user(user)
        #     return redirect(url_for('main.index'))
    kwargs = {
        'title': 'Login',
        'jumbotron': {
            "header": "Log into your account!",
            "text": "Act now for your wellness. "
        },
        'loginPageContents': [{
            'Title': "Login"
        },

        ]
    }
    return render_template('login.html', **kwargs)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

wellness/routes/community.py
from flask import render_template,Blueprint

community_page = Blueprint('community',__name__,template_folder='templates')
@community_page.route('/community',methods=['GET','POST'])

def default_activity_page():
    kwargs = {
        'title': 'Community',
        'jumbotron': {
            "header": "You are not alone.",
            "bg_image": "",
            "text": ""
        },
        'communityPageContents': [{
            'Title': "Forum",
            "Text": " "

        },
            {
            "Title": "Social Media",
            "Text": " "

        },
            {
            "Title": "Other",
            "Text": ""

        }
        ]
    }
    return render_template('community.html', **kwargs)    

wellness/routes/progress.py
from flask import render_template,Blueprint

progress_page = Blueprint('progress',__name__,template_folder='templates')
@progress_page.route('/progress',methods=['GET','POST'])

def default_progress_page():
    kwargs = {
        'title': 'Progress',
        'jumbotron': {
            "header": "Make a progress",
            "bg_image": "static/images/1182_650_gallery.jpeg",
            "text": ""
        }
    }
    return render_template('progress.html', **kwargs)    

wellness/templates/about.html
<!-- Extend base.html to inherit basic layout: navbar, footer -->
{% extends "base.html" %}
<!-- Set active_page, such that current menu is active automatically without hard code -->
{% set active_page = "about" %}
<!-- Set title, template will read title for each html page -->
{% block title %} {{title}} {% endblock %}

<!-- Each page will render differently according to the data to be displayed. -->
{% block content %}
<div class = "container">

    <!-- Try to seperate content from html: write webpage content in aboutPageContents -->
    {% for content in aboutPageContents %}
    <div class = "card border-0">
        <div class="card-body">
            <h5 class="card-title"> {{content["Title"]}}</h5>
            <p class="card-text">{{ content["Text"] }}</p>            

        </div>

    </div>
    <hr>
    {% endfor %}
    <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfyuKIo879WSbAvQkYMxVXJY2gx4iH9_nJxrRGHmHgU4j0rfg/viewform?embedded=true" 
            width="100%" 
            height="1100" 
            frameborder="0" 
            marginheight="0" 
            marginwidth="0">Loading…</iframe>
</div>
{% endblock %}

wellness/templates/activity.html
<!-- Extend base.html to inherit basic layout: navbar, footer -->
{% extends "base.html" %}
<!-- Set active_page, such that current menu is active automatically without hard code -->
{% set active_page = "activity" %}
<!-- Set title, template will read title for each html page -->
{% block title %} {{title}} {% endblock %}

<!-- Each page will render differently according to the data to be displayed. -->
{% block content %}
<div class = "container">
    <!-- Try to seperate content from html: write webpage content in aboutPageContents -->
   <h2>Activities Pool</h2>
   <hr>
    <div class = "row">
        {% for content in activityPageContents %}
        <div class="col-lg-4 col-md-6 col-12">
            <h5 class = "card-title">{{ content["Title"] }}</h5>
            <div class = "card-body">
                <ol>
                    {% for dict_item in content.Activities %}
                    {% for key,value in dict_item.items() %}
                        <li>{{key}}:{{value}}</li>
                    {% endfor %}
                    {% endfor %}
                </ol>
            </div>
        
        
        </div>
        {% endfor %}
    </div>
    <h2>Activities Template</h2>
    <hr>
    <h2>Create Your Own Wellness Plan</h2>
    <hr>
    <h2>Self Assessment</h2>
    <hr>

</div>
{% endblock %}

wellness/templates/base.html
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

    {% block html_head %}{% endblock %}
  </head>

  <body>
      <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">8D Wellness Club</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <ul class="navbar-nav ml-auto">
            {% set navbar_menus = [ ('/', 'home', 'Home'), ('/evidence',
            'evidence', 'Evidence'), ('/activity',
            'activity', 'Activity'), ('/progress', 'progress', 'Progress'),('/community', 'community',
            'Community'), ('/about', 'about', 'About'), 
            ('/register', 'register', 'Register'), ('/login', 'login', 'Login')] -%} 
            <!-- Set active page to style active menu automatically -->
            {% set active_page = active_page|default('home') -%} 
            {% for href, id, caption in navbar_menus %}
              <li class="nav-item">
                <a
                  class="nav-link {% if id == active_page %} active {% endif%}"
                  href="{{ href }}"
                >
                {{ caption }}
              </a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </nav>
      <div class="jumbotron" style = "background-image:url({{jumbotron.bg_image}})">
        <h1 class="display-4">{{jumbotron.header}}</h1>
        <p class = "lead">{{jumbotron.text}} </p>

      </div>

    <!-- Cooperator just need to update the following part based on aggreement on base.html -->
    <div id="content">
      {% block content %}{% endblock %}
    </div>
  
  </body>

  <div class = "pt-4 my-md-5 pt-md-5 border-top">
    <p class="text-center"> © Act Now for your 8D Wellness, 2021</p>
  </div>
</html>

wellness/templates/community.html
<!-- Extend base.html to inherit basic layout: navbar, footer -->
{% extends "base.html" %}
<!-- Set active_page, such that current menu is active automatically without hard code -->
{% set active_page = "community" %}
<!-- Set title, template will read title for each html page -->
{% block title %} {{title}} {% endblock %}

<!-- Each page will render differently according to the data to be displayed. -->
{% block content %}
<div class = "container">

    <!-- Try to seperate content from html: write webpage content in aboutPageContents -->
    {% for content in communityPageContents %}
    <div class = "card border-0">
        <div class="card-body">
            <h5 class="card-title"> {{content["Title"]}}</h5>
            <p class="card-text">{{ content["Text"] }}</p>            

        </div>

    </div>
    <hr>
    {% endfor %}
</div>
{% endblock %}

wellness/templates/evidence.html
<!-- Extend base.html to inherit basic layout: navbar, footer -->
{% extends "base.html" %}
<!-- Set active_page, such that current menu is active automatically without hard code -->
{% set active_page = "evidence" %}
<!-- Set title, template will read title for each html page -->
{% block title %} {{title}} {% endblock %}

<!-- Each page will render differently according to the data to be displayed. -->
{% block content %}
<div class = "container">

    <!-- Try to seperate content from html: write webpage content in aboutPageContents -->
    {% for content in evidencePageContents %}
    <div class = "card border-0">
        <div class="card-body">
            <h5 class="card-title"> {{content["Title"]}}</h5>
            <p class="card-text">
                <ul>
                {% for item in content["Text"] %}
                    <li>{{ item }}</li>
                {% endfor %}
                </ul>
            </p>            

        </div>

    </div>
    <hr>
    {% endfor %}
</div>
{% endblock %}

wellness/templates/home.html
{% extends "base.html" %}
{% set active_page = "home" %}
{% block title %} {{title}} {% endblock %}

{% block content %}

    <div class = "container">
        <!-- Try to seperate content from html: write home page content in homePageContents -->
        {% for content in homePageContents %}
        <div class = "card border-0">
            <div class="card-body">
                <h5 class="card-title"> {{content["Title"]}}
                    <button type="button" class="btn btn-link btn-lg float-right"><a href = {{content["Link"]}}> {{content["Action"]}}</a></button>
                    </h5>
                <p class="card-text">{{ content["Text"] }}</p>            
            </div>
            <img class="card-img-bottom " src={{content["imagePath"] }} alt="Card image cap">
            <hr>
        </div>
        {% endfor %}
    </div>

{% endblock %}

wellness/templates/login.html
{% extends 'base.html' %} {% block title %}Register{% endblock %} {% block
content %}
<div class="container">
  <div class="page-header">
    <h1>Log In</h1>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="well bs-component">
        <form
          class="form-horizontal"
          method="POST"
          action="{{ url_for('auth.register') }}"
        >
          <fieldset>
            <div class="form-group">
              <label for="inputName" class="col-lg-2 control-label">Name</label>
              <div class="col-lg-10">
                <input
                  type="text"
                  class="form-control"
                  name="name"
                  id="inputName"
                  placeholder="Name"
                />
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword" class="col-lg-2 control-label"
                >Password</label
              >
              <div class="col-lg-10">
                <input
                  type="password"
                  class="form-control"
                  name="password"
                  id="inputPassword"
                  placeholder="Password"
                />
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

wellness/templates/logout.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}

{% block content %}
<div class="page-header">
        <h1>Register</h1>
      </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="well bs-component">
              <form class="form-horizontal" method="POST" action="{{ url_for('auth.register') }}">
                <fieldset>
                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">Name</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="name" id="inputName" placeholder="Name">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword" class="col-lg-2 control-label">Password</label>
                    <div class="col-lg-10">
                      <input type="password" class="form-control" name="password" id="inputPassword" placeholder="Password">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Register</button>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>
{% endblock %}

wellness/templates/progress.html
<!-- Extend base.html to inherit basic layout: navbar, footer -->
{% extends "base.html" %}
<!-- Set active_page, such that current menu is active automatically without hard code -->
{% set active_page = "progress" %}
<!-- Set title, template will read title for each html page -->
{% block title %} {{title}} {% endblock %}

<!-- Each page will render differently according to the data to be displayed. -->
{% block content %}
<div class = "container">
    

    <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdOK55p1dhOA8azzcOKztof7OEtjHREoxp9wDanO59EFZBBQA/viewform?embedded=true" 
            width="100%" 
            height="1100" 
            frameborder="0" 
            marginheight="0" 
            marginwidth="0">Loading…</iframe>

    <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSf9cUYibm4EazxxHQJOo6C4rMeQCqjaDMH9dLksDgrgKQkHXA/viewform?embedded=true" 
            width="100%" 
            height="1100" 
            frameborder="0" 
            marginheight="0" 
            marginwidth="0">Loading…</iframe>
</div>
{% endblock %}

wellness/templates/register.html
{% extends 'base.html' %} {% block title %}Register{% endblock %} {% block
content %}
<div class="container">
  <div class="page-header">
    <h1>Register</h1>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="well bs-component">
        <form
          class="form-horizontal"
          method="POST"
          action="{{ url_for('auth.register') }}"
        >
          <fieldset>
            <div class="form-group">
              <label for="inputName" class="col-lg-2 control-label">Name</label>
              <div class="col-lg-10">
                <input
                  type="text"
                  class="form-control"
                  name="name"
                  id="inputName"
                  placeholder="Name"
                />
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword" class="col-lg-2 control-label"
                >Password</label
              >
              <div class="col-lg-10">
                <input
                  type="password"
                  class="form-control"
                  name="password"
                  id="inputPassword"
                  placeholder="Password"
                />
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>
          </fieldset>
        </form>
      </div>
    </div>
    {% endblock %}
  </div>
</div>